// Code generated by MockGen. DO NOT EDIT.
// Source: producer.go

// Package mock_stream is a generated GoMock package.
package mock_stream

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockID is a mock of id interface.
type MockID struct {
	ctrl     *gomock.Controller
	recorder *MockIDMockRecorder
}

// MockIDMockRecorder is the mock recorder for MockID.
type MockIDMockRecorder struct {
	mock *MockID
}

// NewMockID creates a new mock instance.
func NewMockID(ctrl *gomock.Controller) *MockID {
	mock := &MockID{ctrl: ctrl}
	mock.recorder = &MockIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockID) EXPECT() *MockIDMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockID) GetID() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockIDMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockID)(nil).GetID))
}
