---
name: Build & Tests

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

jobs:
  build:
    name: Build and unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
#        go-version: oldstable

    - name: Build
      run: make build

    - name: Test
      run: make tests-ci
      env:
        RABBITMQ_STREAM_SKIP_RABBIT_START: "for system tests"

  e2e_test:
    name: E2E Test
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: "rabbitmq:3-management"
        ports:
          - 5552
          - 5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics check_running"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
#          go-version: oldstable

      - name: E2E Tests
        env:
          RABBITMQ_CONTAINER_NAME: ${{ job.services.rabbitmq.id }}
        run: make e2e_tests RMQ_E2E_SKIP_CONTAINER_START="please" RABBITMQ_URI="rabbitmq-stream://guest:guest@localhost:${{ job.services.rabbitmq.ports[5552] }}/%2F" CI="actions"
