name: Publish Docker image

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    needs: [ test, test-win32 ]
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Publish Docker Image
        run: |
          set -x
          VERSION=latest
          export VERSION
          if [[ ! $GITHUB_REF =~ "/tags/" ]]
          then
            VERSION=dev
          fi
          make perf-test-docker-push
